version: "3.3"
services:
  hop-web:
    user: 0:0
    image: apache/hop-web:${SOFTWARE_VERSION_TAG}
    ports:
      - "172.17.0.1:13543:8080"
    volumes:
      - ./storage/project:/project
      - ./storage/project:/config
    environment:
      - HOP_PROJECT_FOLDER=/project
      - HOP_PROJECT_NAME=default-project
      - HOP_ENVIRONMENT_NAME=default-project-env
      - HOP_CONFIG_FOLDER=/config
      - HOP_SERVER_HOSTNAME=hop-server
      - HOP_SERVER_PORT=8080
      - HOP_LOG_LEVEL=BASIC
    restart: always
