version: "3.3"
services:
  hop:
    image: "apache/hop:latest"
    restart: always
    environment:
      - HOP_SERVER_USER=root
      - HOP_SERVER_PASS=${ADMIN_PASSWORD}
      - HOP_SERVER_SHUTDOWNPORT=8080
      - HOP_SERVER_PORT=8181
      - HOP_SERVER_PORT=8180
      - HOP_SERVER_HOSTNAME=172.17.0.1
    ports:
      - "172.17.0.1:8080:8080"
      - "172.17.0.1:8181:8181"
      - "172.17.0.1:8180:8180"
